### ISSUE TITLE
public1 svc/httpsvc type loadbalancer

### ISSUE THREAD

**Issue by elmomk** [skupperproject/skupper-example-http-load-balancing#1]
When the type of svc/httpsvc is changed to loadbalancer on public1, should the requests be balanced equally between the pod/httpsvc proxy created by skupper and the pod/http-server?

When I tried this out it basically just redirected the traffic to the pod/http-server on public1 but didn't balance it with private1.
When I changed the type of svc/httpsvc to loadbalancer on public2, it did balance all the traffic equally between public1 and private1.

My question is: Could I get the same equally divided loadbalancing effect without having the traffic go through public2 but directly from public1 with svc/httpsvc on type loadbalancer so the outside world can reach this svc as well?

**Comment by pwright** [comment]
I've tested this with https://github.com/skupperproject/skupper/releases/tag/1.4.0-rc2

using https://github.com/pwright/skupper-example-http-load-balancing/tree/main

and I believe the issue has been resolved

**Comment by ssorj** [comment]
This was fixed in https://github.com/skupperproject/skupper-router/issues/867
